# =========================================================
# CONFIGURAÇÕES DO BANCO DE DADOS
# Sistema Locadora - Programação III
# =========================================================

# Tipo de banco usado pelo sistema
db.driver=postgresql

# endereço do servidor do banco
db.host=localhost

# Porta padrÃ£o do PostgreSQL
db.port=5432

# Nome do Banco de dados
db.name=locadora_db

# UsuÃ¡rio do Banco
db.user=postgres

# Senha do Banco
db.password=123456
