# =========================================================
# CONFIGURAÇÕES DO BANCO DE DADOS
# Sistema Locadora - Programação III
# =========================================================

# Tipo de banco usado pelo sistema
db.driver=postgresql

# Endereço do servidor do banco
db.host=localhost

# Porta padrão do PostgreSQL
db.port=5432

# Nome do banco de dados
db.name=locadora_db

# Usuário do banco
db.user=postgres

# Senha do banco
db.password=123456