# =========================================================
# CONFIGURA«’ES DO BANCO DE DADOS
# Sistema Locadora - ProgramaÁ„o III
# =========================================================

# Tipo de banco usado pelo sistema
db.driver=postgresql

# Endere√ßo do servidor do banco
db.host=localhost

# Porta padr√£o do PostgreSQL
db.port=5432

# Nome do banco de dados
db.name=locadora_db

# Usu√°rio do banco
db.user=postgres

# Senha do banco
db.password=123456
